strava_authorization_link: 'https://www.strava.com/oauth/authorize?client_id=35525&response_type=code&redirect_uri=https://bnr-statistic.herokuapp.com&approval_prompt=force&scope=read,activity:read'
strava_client_id: '35525'
strava_client_secret: 'f778b9cb5a6dc18bb2edd19acf18c6d8095c04c7'
